import 'hammerjs';
import { NgModule, ErrorHandler } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

import { 	
	MatCommonModule,
	MatAutocompleteModule,
	MatBottomSheetModule,
	MatButtonToggleModule,  
	MatDialogModule,
	MatInputModule,
	MatButtonModule, 
	MatCheckboxModule,
	MatFormFieldModule,
	MatMenuModule,
	MatPaginatorModule,
	MatGridListModule,
	MatRippleModule,
	MatPseudoCheckboxModule,
	MatLineModule,
	MatOptionModule,
	MatNativeDateModule,
	MatCardModule,
	MatBadgeModule,
	MatChipsModule,
	MatExpansionModule,
	MatDividerModule,
	MatListModule,
	MatSelectModule,
	MatRadioModule,
	MatProgressSpinnerModule,
	MatProgressBarModule,
	MatSidenavModule,
	MatSlideToggleModule,
	MatSliderModule,
	MatSnackBarModule,
	MatSortModule,
	MatStepperModule,
	MatTableModule,
	MatTabsModule,
	MatToolbarModule,
	MatTooltipModule,
	MatTreeModule
	 } from '@angular/material';

import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],

  imports: [
	MatCommonModule,
	MatAutocompleteModule,
	MatBottomSheetModule,
	MatButtonToggleModule,  
	MatDialogModule,
	MatInputModule,
	MatButtonModule, 
	MatCheckboxModule,
	MatFormFieldModule,
	MatMenuModule,
	MatPaginatorModule,
	MatGridListModule,
	MatRippleModule,
	MatPseudoCheckboxModule,
	MatLineModule,
	MatOptionModule,
	MatNativeDateModule,
	MatCardModule,
	MatBadgeModule,
	MatChipsModule,
	MatExpansionModule,
	MatDividerModule,
	MatListModule,
	MatSelectModule,
	MatRadioModule,
	MatProgressSpinnerModule,
	MatProgressBarModule,
	MatSidenavModule,
	MatSlideToggleModule,
	MatSliderModule,
	MatSnackBarModule,
	MatSortModule,
	MatStepperModule,
	MatTableModule,
	MatTabsModule,
	MatToolbarModule,
	MatTooltipModule,
	MatTreeModule,
	BrowserModule,
	BrowserAnimationsModule
  ],
  exports: [
	MatCommonModule,
	MatAutocompleteModule,
	MatBottomSheetModule,
	MatButtonToggleModule,  
	MatDialogModule,
	MatInputModule,
	MatButtonModule, 
	MatCheckboxModule,
	MatFormFieldModule,
	MatMenuModule,
	MatPaginatorModule,
	MatGridListModule,
	MatRippleModule,
	MatPseudoCheckboxModule,
	MatLineModule,
	MatOptionModule,
	MatNativeDateModule,
	MatCardModule,
	MatBadgeModule,
	MatChipsModule,
	MatExpansionModule,
	MatDividerModule,
	MatListModule,
	MatSelectModule,
	MatRadioModule,
	MatProgressSpinnerModule,
	MatProgressBarModule,
	MatSidenavModule,
	MatSlideToggleModule,
	MatSliderModule,
	MatSnackBarModule,
	MatSortModule,
	MatStepperModule,
	MatTableModule,
	MatTabsModule,
	MatToolbarModule,
	MatTooltipModule,
	MatTreeModule,
	BrowserModule,
	BrowserAnimationsModule
  ],
  providers: [ErrorHandler],
  bootstrap: [AppComponent]
})
export class AppModule {}
